# Policy for: .github/workflows/release.yml in DataDog/swift-code-coverage
issuer: https://token.actions.githubusercontent.com
subject: repo:DataDog/swift-code-coverage:ref:refs/heads/main

claim_pattern:
  event_name: workflow_dispatch
  job_workflow_ref: DataDog/swift-code-coverage/\.github/workflows/release\.yml@refs/heads/main
  ref: refs/heads/main
  repository: DataDog/swift-code-coverage

permissions:
  contents: write
