name: Build LLVM XCFrameworks
on:
  workflow_call:
    outputs:
      llvm19-cache-key:
        description: "Cache key for LLVM19.xcframework"
        value: ${{ jobs.build-xcframework.outputs.llvm19 }}
      llvm17-cache-key:
        description: "Cache key for LLVM17.xcframework"
        value: ${{ jobs.build-xcframework.outputs.llvm17 }}
      llvm16-cache-key:
        description: "Cache key for LLVM16.xcframework"
        value: ${{ jobs.build-xcframework.outputs.llvm16 }}
permissions:
  contents: read
jobs:
  build-llvm-libs:
    runs-on: macos-13
    strategy:
      matrix:
        version: [16, 17, 19]
        platform: [macosx, maccatalyst, iphoneos, iphonesimulator, appletvos, appletvsimulator]
    outputs:
      macosx16: ${{ steps.llvm-cache-key.outputs.llvm16_macosx }}
      macosx17: ${{ steps.llvm-cache-key.outputs.llvm17_macosx }}
      macosx19: ${{ steps.llvm-cache-key.outputs.llvm19_macosx }}
      maccatalyst16: ${{ steps.llvm-cache-key.outputs.llvm16_maccatalyst }}
      maccatalyst17: ${{ steps.llvm-cache-key.outputs.llvm17_maccatalyst }}
      maccatalyst19: ${{ steps.llvm-cache-key.outputs.llvm19_maccatalyst }}
      iphoneos16: ${{ steps.llvm-cache-key.outputs.llvm16_iphoneos }}
      iphoneos17: ${{ steps.llvm-cache-key.outputs.llvm17_iphoneos }}
      iphoneos19: ${{ steps.llvm-cache-key.outputs.llvm19_iphoneos }}
      iphonesimulator16: ${{ steps.llvm-cache-key.outputs.llvm16_iphonesimulator }}
      iphonesimulator17: ${{ steps.llvm-cache-key.outputs.llvm17_iphonesimulator }}
      iphonesimulator19: ${{ steps.llvm-cache-key.outputs.llvm19_iphonesimulator }}
      appletvos16: ${{ steps.llvm-cache-key.outputs.llvm16_appletvos }}
      appletvos17: ${{ steps.llvm-cache-key.outputs.llvm17_appletvos }}
      appletvos19: ${{ steps.llvm-cache-key.outputs.llvm19_appletvos }}
      appletvsimulator16: ${{ steps.llvm-cache-key.outputs.llvm16_appletvsimulator }}
      appletvsimulator17: ${{ steps.llvm-cache-key.outputs.llvm17_appletvsimulator }}
      appletvsimulator19: ${{ steps.llvm-cache-key.outputs.llvm19_appletvsimulator }}
    timeout-minutes: 1200
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Calculate and save cache key for llvm library
        id: llvm-cache-key
        run: |
          HASH=${{ hashFiles('llvm/patches/**', 'Makefile.llvm') }}
          KEY="llvm${{ matrix.version }}-${{ matrix.platform }}-$HASH"
          echo "llvm_current=$KEY" >> "$GITHUB_OUTPUT"
          echo "llvm${{matrix.version}}_${{matrix.platform}}=$KEY" >> "$GITHUB_OUTPUT"
      - name: Check cache for built binary
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        id: llvm-build-cache
        with:
          path: llvm/build/libs/llvm${{ matrix.version }}/${{ matrix.platform }}
          key: ${{ steps.llvm-cache-key.outputs.llvm_current }}
          lookup-only: true
      - name: Select Xcode 14.3.1
        if: steps.llvm-build-cache.outputs.cache-hit != 'true'
        run: sudo xcode-select --switch /Applications/Xcode_14.3.1.app
      - name: Build LLVM ${{ matrix.version }} for ${{ matrix.platform }}
        if: steps.llvm-build-cache.outputs.cache-hit != 'true'
        run: make -f Makefile.llvm llvm/build/libs/llvm${{ matrix.version }}/${{ matrix.platform }}

  build-xcframework:
    needs: build-llvm-libs
    runs-on: macos-latest
    strategy:
      matrix:
        version: [16, 17, 19]
    outputs:
      llvm16: ${{ steps.llvm-cache-key.outputs.llvm16_framework }}
      llvm17: ${{ steps.llvm-cache-key.outputs.llvm17_framework }}
      llvm19: ${{ steps.llvm-cache-key.outputs.llvm19_framework }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Calculate and save cache key for llvm framework
        id: llvm-cache-key
        run: |
          HASH=${{ hashFiles('llvm/patches/**', 'Makefile.llvm') }}
          KEY="llvm${{ matrix.version }}-framework-$HASH"
          echo "llvm_current=$KEY" >> "$GITHUB_OUTPUT"
          echo "llvm${{matrix.version}}_framework=$KEY" >> "$GITHUB_OUTPUT"
      - name: Check cache for built binary
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        id: llvm-build-cache
        with:
          path: llvm/xcframeworks/LLVM${{ matrix.version }}.xcframework
          key: ${{ steps.llvm-cache-key.outputs.llvm_current }}
          lookup-only: true
      - name: Download llvm ${{matrix.version}} for macosx
        if: steps.llvm-build-cache.outputs.cache-hit != 'true'
        uses: actions/cache/restore@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: llvm/build/libs/llvm${{matrix.version}}/macosx
          key: ${{ needs.build-llvm-libs.outputs[format('macosx{0}', matrix.version)] }}
          fail-on-cache-miss: true
      - name: Download llvm ${{matrix.version}} for maccatalyst
        if: steps.llvm-build-cache.outputs.cache-hit != 'true'
        uses: actions/cache/restore@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: llvm/build/libs/llvm${{matrix.version}}/maccatalyst
          key: ${{ needs.build-llvm-libs.outputs[format('maccatalyst{0}', matrix.version)] }}
          fail-on-cache-miss: true
      - name: Download llvm ${{matrix.version}} for iphoneos
        if: steps.llvm-build-cache.outputs.cache-hit != 'true'
        uses: actions/cache/restore@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: llvm/build/libs/llvm${{matrix.version}}/iphoneos
          key: ${{ needs.build-llvm-libs.outputs[format('iphoneos{0}', matrix.version)] }}
          fail-on-cache-miss: true
      - name: Download llvm ${{matrix.version}} for iphonesimulator
        if: steps.llvm-build-cache.outputs.cache-hit != 'true'
        uses: actions/cache/restore@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: llvm/build/libs/llvm${{matrix.version}}/iphonesimulator
          key: ${{ needs.build-llvm-libs.outputs[format('iphonesimulator{0}', matrix.version)] }}
          fail-on-cache-miss: true
      - name: Download llvm ${{matrix.version}} for appletvos
        if: steps.llvm-build-cache.outputs.cache-hit != 'true'
        uses: actions/cache/restore@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: llvm/build/libs/llvm${{matrix.version}}/appletvos
          key: ${{ needs.build-llvm-libs.outputs[format('appletvos{0}', matrix.version)] }}
          fail-on-cache-miss: true
      - name: Download llvm ${{matrix.version}} for appletvsimulator
        if: steps.llvm-build-cache.outputs.cache-hit != 'true'
        uses: actions/cache/restore@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: llvm/build/libs/llvm${{matrix.version}}/appletvsimulator
          key: ${{ needs.build-llvm-libs.outputs[format('appletvsimulator{0}', matrix.version)] }}
          fail-on-cache-miss: true
      - name: Create XCFrameworks
        if: steps.llvm-build-cache.outputs.cache-hit != 'true'
        run: make -f Makefile.llvm llvm${{matrix.version}}_prebuilt_xcframework
