name: Publish new release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version'
        required: true
        type: string
permissions:
  contents: read
jobs:
  test:
    uses: "./.github/workflows/test.yml"
  release:
    needs: test
    runs-on: macos-26
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Download LLVM19 framework
        uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: llvm/xcframeworks/LLVM19.xcframework
          key: ${{ needs.test.outputs.llvm19-cache-key }}
          fail-on-cache-miss: true
      - name: Select Xcode 26.2
        run: sudo xcode-select --switch /Applications/Xcode_26.2.app
      - name: Build and upload XCFrameworks, create tag and release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make XC_LOG=archive version=${{ github.event.inputs.version }} github_release
      - name: Attach Xcode logs
        if: '!cancelled()'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: xcode-archive-logs
          path: "*-archive.log"
