name: Publish new release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version'
        required: true
        type: string
permissions:
  contents: read
jobs:
  test:
    uses: "./.github/workflows/test.yml"
  release:
    needs: test
    runs-on: macos-13
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Download LLVM15 framework
        uses: actions/cache/restore@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: llvm/xcframeworks/LLVM15.xcframework
          key: ${{ needs.test.outputs.llvm15-cache-key }}
          fail-on-cache-miss: true
      - name: Download LLVM17 framework
        uses: actions/cache/restore@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: llvm/xcframeworks/LLVM17.xcframework
          key: ${{ needs.test.outputs.llvm17-cache-key }}
          fail-on-cache-miss: true
      - name: Select Xcode 14.3.1
        run: sudo xcode-select --switch /Applications/Xcode_14.3.1.app
      - name: Build and upload XCFrameworks, create tag and release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make XC_LOG=archive version=${{ github.event.inputs.version }} github_release
      - name: Attach Xcode logs
        if: '!cancelled()'
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: xcode-archive-logs
          path: "*-archive.log"
