name: Run Tests
on:
  pull_request:
  workflow_dispatch:
  workflow_call:
    outputs:
      llvm19-cache-key:
        description: "Cache key for LLVM19.xcframework"
        value: ${{ jobs.build-llvm.outputs.llvm19-cache-key }}
permissions:
  contents: read
jobs:
  build-llvm:
    uses: "./.github/workflows/build-llvm.yml"
  test:
    needs: build-llvm
    strategy:
      matrix:
        xcode:
          - os: macos-26
            xcode: "26.2"
            iossim: "iPhone 17"
            watchossim: "Apple Watch Series 11 (46mm)"
    runs-on: ${{ matrix.xcode.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Download LLVM19 framework
        uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: llvm/xcframeworks/LLVM19.xcframework
          key: ${{ needs.build-llvm.outputs.llvm19-cache-key }}
          fail-on-cache-miss: true
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode.xcode }}.app
      - name: Build CodeCoverageParser for SPM tests
        run: make XC_LOG=build build
      - name: Run tests for all platforms
        run: make IOS_SIMULATOR="${{ matrix.xcode.iossim }}" WATCHOS_SIMULATOR="${{ matrix.xcode.watchossim }}" XC_LOG=tests test
      - name: Attach Xcode test logs
        if: '!cancelled()'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: xcode${{ matrix.xcode.xcode }}-tests-logs
          path: "*-tests.log"
      - name: Attach Xcode build logs
        if: '!cancelled()'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: xcode${{ matrix.xcode.xcode }}-build-logs
          path: "*-build.log"
