name: Run Tests
on:
  push:
  pull_request:
  workflow_call:
    outputs:
      llvm17-cache-key:
        description: "Cache key for LLVM17.xcframework"
        value: ${{ jobs.build-llvm.outputs.llvm17-cache-key }}
      llvm15-cache-key:
        description: "Cache key for LLVM15.xcframework"
        value: ${{ jobs.build-llvm.outputs.llvm15-cache-key }}
permissions:
  contents: read
jobs:
  build-llvm:
    uses: "./.github/workflows/build-llvm.yml"
  test:
    needs: build-llvm
    strategy:
      matrix:
        xcode:
          - os: macos-latest
            xcode: "16.1"
          - os: macos-14
            xcode: "15.4"
          - os: macos-13
            xcode: "14.3.1"
    runs-on: ${{ matrix.xcode.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download LLVM15 framework
        uses: actions/cache/restore@v4
        with:
          path: llvm/xcframeworks/LLVM15.xcframework
          key: ${{ needs.build-llvm.outputs.llvm15-cache-key }}
          fail-on-cache-miss: true
      - name: Download LLVM17 framework
        uses: actions/cache/restore@v4
        with:
          path: llvm/xcframeworks/LLVM17.xcframework
          key: ${{ needs.build-llvm.outputs.llvm17-cache-key }}
          fail-on-cache-miss: true
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode.xcode }}.app
      - name: Run tests for all platforms
        run: make test
